### ISSUE TITLE
Bug: `import ValidationProvider` doesn't work.

### ISSUE THREAD

**Issue by martinlasek** [vapor/validation-provider#8]
If you are using the latest package and try to `import ValidationProvider` it would result in `no such module`. However it is working the **old** way: `import VaporValidation`.

Fix the package so `import ValidationProvider` would work instead of `import VaporValidation`.

**Comment by tanner0101** [comment]
Oops. That should be `ValidationProvider`. The fix will unfortunately need to wait until the next version since it's a breaking change.
